In [1]:
import pandas as pd
import warnings

warnings.filterwarnings(action='ignore')

In [2]:
complaints_data = pd.read_csv("Consumer_Complaints.csv", sep=",")
complaints_data.head()

Date received                  Product                  Sub-product  \
0    07/29/2013            Consumer Loan                 Vehicle loan   
1    07/29/2013  Bank account or service             Checking account   
2    07/29/2013  Bank account or service             Checking account   
3    07/29/2013  Bank account or service             Checking account   
4    07/29/2013                 Mortgage  Conventional fixed mortgage   

                                      Issue Sub-issue  \
0                Managing the loan or lease       NaN   
1                 Using a debit or ATM card       NaN   
2   Account opening, closing, or management       NaN   
3                  Deposits and withdrawals       NaN   
4  Loan servicing, payments, escrow account       NaN   

  Consumer complaint narrative Company public response  \
0                          NaN                     NaN   
1                          NaN                     NaN   
2                          NaN                     NaN   
3                          NaN                     NaN   
4                          NaN                     NaN   

                      Company State ZIP code            Tags  \
0       Wells Fargo & Company    VA    24540             NaN   
1       Wells Fargo & Company    CA    95992  Older American   
2           Santander Bank US    NY    10065             NaN   
3       Wells Fargo & Company    GA    30084             NaN   
4  Franklin Credit Management    CT    06106             NaN   

  Consumer consent provided? Submitted via Date sent to company  \
0                        NaN         Phone           07/30/2013   
1                        NaN           Web           07/31/2013   
2                        NaN           Fax           07/31/2013   
3                        NaN           Web           07/30/2013   
4                        NaN           Web           07/30/2013   

  Company response to consumer Timely response? Consumer disputed?  \
0      Closed with explanation              Yes                 No   
1      Closed with explanation              Yes                 No   
2                       Closed              Yes                 No   
3      Closed with explanation              Yes                 No   
4      Closed with explanation              Yes                 No   

   Complaint ID  
0        468882  
1        468889  
2        468879  
3        468949  
4        475823

In [3]:
complaints_data.shape

(670598, 18)

In [4]:
complaints_data.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Consumer consent provided?',
       'Submitted via', 'Date sent to company', 'Company response to consumer',
       'Timely response?', 'Consumer disputed?', 'Complaint ID'],
      dtype='object')

In [5]:
data = complaints_data[['Product','Sub-product', 'Issue', 'Company', 'State', 'Submitted via']]

In [6]:
data

Product                             Sub-product  \
0                 Consumer Loan                            Vehicle loan   
1       Bank account or service                        Checking account   
2       Bank account or service                        Checking account   
3       Bank account or service                        Checking account   
4                      Mortgage             Conventional fixed mortgage   
...                         ...                                     ...   
670593         Credit reporting                                     NaN   
670594                 Mortgage  Conventional adjustable mortgage (ARM)   
670595         Credit reporting                                     NaN   
670596              Credit card                                     NaN   
670597            Consumer Loan                        Installment loan   

                                           Issue                     Company  \
0                     Managing the loan or lease       Wells Fargo & Company   
1                      Using a debit or ATM card       Wells Fargo & Company   
2        Account opening, closing, or management           Santander Bank US   
3                       Deposits and withdrawals       Wells Fargo & Company   
4       Loan servicing, payments, escrow account  Franklin Credit Management   
...                                          ...                         ...   
670593    Incorrect information on credit report                     Equifax   
670594  Loan modification,collection,foreclosure                    Citibank   
670595    Incorrect information on credit report                     Equifax   
670596                Closing/Cancelling account                        Amex   
670597                Managing the loan or lease           BancorpSouth Bank   

       State Submitted via  
0         VA         Phone  
1         CA           Web  
2         NY           Fax  
3         GA           Web  
4         CT           Web  
...      ...           ...  
670593    NV           Web  
670594    UT           Web  
670595    TN           Web  
670596    FL           Web  
670597    MS           Web  

[670598 rows x 6 columns]

In [7]:
data02 = data.dropna(how="any")

In [8]:
data02

Product                             Sub-product  \
0                 Consumer Loan                            Vehicle loan   
1       Bank account or service                        Checking account   
2       Bank account or service                        Checking account   
3       Bank account or service                        Checking account   
4                      Mortgage             Conventional fixed mortgage   
...                         ...                                     ...   
670587          Debt collection   Other (i.e. phone, health club, etc.)   
670589          Debt collection   Other (i.e. phone, health club, etc.)   
670592                 Mortgage                          Other mortgage   
670594                 Mortgage  Conventional adjustable mortgage (ARM)   
670597            Consumer Loan                        Installment loan   

                                           Issue                     Company  \
0                     Managing the loan or lease       Wells Fargo & Company   
1                      Using a debit or ATM card       Wells Fargo & Company   
2        Account opening, closing, or management           Santander Bank US   
3                       Deposits and withdrawals       Wells Fargo & Company   
4       Loan servicing, payments, escrow account  Franklin Credit Management   
...                                          ...                         ...   
670587                     Communication tactics            Gross Polowy LLC   
670589     Cont'd attempts collect debt not owed     Transworld Systems Inc.   
670592  Loan modification,collection,foreclosure       Wells Fargo & Company   
670594  Loan modification,collection,foreclosure                    Citibank   
670597                Managing the loan or lease           BancorpSouth Bank   

       State Submitted via  
0         VA         Phone  
1         CA           Web  
2         NY           Fax  
3         GA           Web  
4         CT           Web  
...      ...           ...  
670587    NY   Postal mail  
670589    MO           Web  
670592    WA      Referral  
670594    UT           Web  
670597    MS           Web  

[468289 rows x 6 columns]

In [9]:
data02.shape

(468289, 6)

In [10]:
print(data02['Product'].value_counts())
print()
print(data02['Sub-product'].value_counts())
print()
print(data02['Issue'].value_counts())
print()
print(data02['Company'].value_counts())
print()
print(data02['State'].value_counts())
print()
print(data02['Submitted via'].value_counts())

Mortgage                   208905
Debt collection            123488
Bank account or service     74707
Consumer Loan               26444
Student loan                21504
Payday loan                  4765
Money transfers              4540
Prepaid card                 3135
Other financial service       788
Virtual currency               13
Name: Product, dtype: int64

Other mortgage                            80710
Conventional fixed mortgage               64842
Checking account                          52184
Other (i.e. phone, health club, etc.)     36923
I do not know                             25858
Credit card                               24988
Conventional adjustable mortgage (ARM)    23551
FHA mortgage                              22252
Non-federal student loan                  20558
Medical                                   17066
Vehicle loan                              15023
Other bank product/service                14280
Payday loan                               11400
Home eq

#### complains!!  
* Product:       Mortgage  
* Sub-product:   Other mortgage  
* Issue:         Loan modification,collection,foreclosure  
* Company:       Bank of America  
* State:         CA (California)  
* Submitted via: Web  

### Y = <span style="color:brown">'Submitted Via'</span>

In [11]:
data03 = pd.DataFrame(columns=['Product','Sub-product', 'Issue', 'Company', 'State', 'Submitted via'])

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data03['Product'] = le.fit_transform(data02['Product'])
data03['Sub-product'] = le.fit_transform(data02['Sub-product'])
data03['Issue'] = le.fit_transform(data02['Issue'])
data03['Company'] = le.fit_transform(data02['Company'])
data03['State'] = le.fit_transform(data02['State'])
data03['Submitted via'] = le.fit_transform(data02['Submitted via'])

In [13]:
data03

Product  Sub-product  Issue  Company  State  Submitted via
0             1           46     38     3808     55              2
1             0            4     57     3808      8              5
2             0            4      0     3182     42              1
3             0            4     17     3808     15              5
4             4            6     33     1514     10              5
...         ...          ...    ...      ...    ...            ...
468284        2           29     12     1670     42              3
468285        2           29     13     3598     31              5
468286        4           31     32     3808     58              4
468287        4            5     32      810     54              5
468288        1           22     38      480     33              5

[468289 rows x 6 columns]

In [14]:
X  = data03[['Product','Sub-product', 'Issue', 'Company', 'State']].values 

In [15]:
X[:10]

array([[   1,   46,   38, 3808,   55],
       [   0,    4,   57, 3808,    8],
       [   0,    4,    0, 3182,   42],
       [   0,    4,   17, 3808,   15],
       [   4,    6,   33, 1514,   10],
       [   0,    4,   17,  481,   53],
       [   2,   29,   13, 2453,   55],
       [   2,   20,   13, 3414,   13],
       [   4,   31,   33, 3808,   41],
       [   4,   31,   32,  481,   35]])

In [16]:
Y = data03['Submitted via'].values

In [17]:
Y[:10]

array([2, 5, 1, 5, 5, 5, 5, 4, 4, 4])

In [18]:
from sklearn import preprocessing

X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))

In [19]:
X[:10]

array([[-0.97648739,  2.08986615,  0.88235619,  1.49063904,  1.525281  ],
       [-1.49553494, -1.21317037,  2.23025046,  1.49063904, -1.19613138],
       [-1.49553494, -1.21317037, -1.81343235,  0.96894175,  0.77254992],
       [-1.49553494, -1.21317037, -0.60742169,  1.49063904, -0.79081464],
       [ 0.58065528, -1.05588292,  0.52764717, -0.42113984, -1.08032659],
       [-1.49553494, -1.21317037, -0.60742169, -1.28202371,  1.40947622],
       [-0.45743983,  0.7529228 , -0.8911889 ,  0.36140609,  1.525281  ],
       [-0.45743983,  0.04512926, -0.8911889 ,  1.16228643, -0.90661942],
       [ 0.58065528,  0.91021025,  0.52764717,  1.49063904,  0.71464753],
       [ 0.58065528,  0.91021025,  0.45670537, -1.28202371,  0.36723318]])

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)

In [ ]:
'''
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt

train_acc = []
test_acc = []

for n in range(1,21):
    clf = KNeighborsClassifier(n_jobs=-1, n_neighbors=n)
    clf.fit(X_train, Y_train)
    prediction = clf.predict(X_test)
    train_acc.append(clf.score(X_train, Y_train))
    test_acc.append((prediction==Y_test).mean())
    
plt.figure(figsize=(12, 9))
plt.plot(range(1, 21), train_acc, label='TRAIN set')
plt.plot(range(1, 21), test_acc, label='TEST set')
plt.xlabel("n_neighbors")
plt.ylabel("accuracy")
plt.xticks(np.arange(0, 21, step=1))
plt.legend()
'''

It takes long time, so I run it on Google colab and replace the result as an image below!

![Accuracy](Accuracy.png)

It seems like test accuracy continuously increase if K increases.

#### KNN

In [22]:
from sklearn.neighbors import KNeighborsClassifier

k = 45
my_model = KNeighborsClassifier(n_neighbors=k).fit(X_train, Y_train)
Ypredict = my_model.predict(X_test)

In [23]:
from sklearn import metrics

print('accuracy score of train: ',   metrics.accuracy_score(Y_train, my_model.predict(X_train)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, Ypredict))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, my_model.predict(X_train), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, Ypredict, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, my_model.predict(X_train), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, Ypredict, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, my_model.predict(X_train)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, Ypredict))

accuracy score of train:  0.7385952495713876
accuracy score of test:  0.7342387551873127

recall score of train:  0.7385952495713876
recall score of test:  0.7342387551873127

precision score of train:  0.7385952495713876
precision score of test:  0.7342387551873127

confusion_matrix of train:  [[     0      0      1      2     80     96]
 [     0    532     11     52   2242   2005]
 [     0     10    248     12   3549  22852]
 [     0    114     37    788   7033   7519]
 [     0    524    106    442  42556  26099]
 [     0     69    202     16  12616 197989]]
confusion_matrix of test:  [[    0     0     0     0    31    31]
 [    0   196     7    21   978   825]
 [    0    10    82     5  1537  9819]
 [    0    43    21   308  3033  3242]
 [    0   205    51   214 18025 11429]
 [    0    38    89     6  5701 84540]]


#### LDA

In [24]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA()
X_train02 = lda.fit_transform(X_train, Y_train)
X_test02 = lda.transform(X_test)
y_predicted_test = lda.predict(X_test) 

In [25]:
print('accuracy score of train: ',   metrics.accuracy_score(Y_train, lda.predict(X_train02)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, y_predicted_test))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, lda.predict(X_train02), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, y_predicted_test, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, lda.predict(X_train02), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, y_predicted_test, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, lda.predict(X_train02)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, y_predicted_test))

accuracy score of train:  0.603443542138242
accuracy score of test:  0.6198509470627176

recall score of train:  0.603443542138242
recall score of test:  0.6198509470627176

precision score of train:  0.603443542138242
precision score of test:  0.6198509470627176

confusion_matrix of train:  [[     0      0      0      0      4    175]
 [     0      0      0      0     87   4755]
 [     0      0      0      0    745  25926]
 [     0      0      0      0    302  15189]
 [     0      0      0      0   1130  68597]
 [     0      0      0      0  14212 196680]]
confusion_matrix of test:  [[    0     0     0     0     1    61]
 [    0     0     0     0    69  1958]
 [    0     0     0     0   517 10936]
 [    0     0     0     0   206  6441]
 [    0     0     0     0   611 29313]
 [    0     0     0     0  3904 86470]]


#### LogisticRegression

In [26]:
from sklearn.linear_model import LogisticRegression

linear = LogisticRegression()
linear.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [27]:
print('accuracy score of test: ', linear.score(X_test, Y_test))

accuracy score of test:  0.6204986938293223


Opinion:  
Focusing mainly on KNN and LDA, KNN seems working better when letting Y as 'Submitted via' in my analysis.  
Plus, when I search loglinear, logistic regression pops up. So, I add the score of that method briefly.  
By the way, It seems hard to find optimal K at KNN!

### Y = <span style="color:brown">'State'</span>

In [28]:
X  = data03[['Product','Sub-product', 'Issue', 'Company', 'Submitted via']].values
Y = data03['State'].values

In [29]:
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))

In [30]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)

#### KNN

In [31]:
k = 100
my_model = KNeighborsClassifier(n_neighbors=k).fit(X_train, Y_train)
Ypredict = my_model.predict(X_test)

In [32]:
print('accuracy score of train: ',   metrics.accuracy_score(Y_train, my_model.predict(X_train)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, Ypredict))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, my_model.predict(X_train), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, Ypredict, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, my_model.predict(X_train), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, Ypredict, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, my_model.predict(X_train)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, Ypredict))

accuracy score of train:  0.1789250828243879
accuracy score of test:  0.1673820353484664

recall score of train:  0.1789250828243879
recall score of test:  0.1673820353484664

precision score of train:  0.1789250828243879
precision score of test:  0.1673820353484664

confusion_matrix of train:  [[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ... 24  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  1  0  0]]
confusion_matrix of test:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 6 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### LDA

In [33]:
lda = LDA()
X_train02 = lda.fit_transform(X_train, Y_train)
X_test02 = lda.transform(X_test)
y_predicted_test = lda.predict(X_test) 

In [34]:
print('accuracy score of train: ',   metrics.accuracy_score(Y_train, lda.predict(X_train02)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, y_predicted_test))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, lda.predict(X_train02), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, y_predicted_test, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, lda.predict(X_train02), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, y_predicted_test, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, lda.predict(X_train02)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, y_predicted_test))

accuracy score of train:  0.15185996424670992
accuracy score of test:  0.1532027874465253

recall score of train:  0.15185996424670992
recall score of test:  0.1532027874465253

precision score of train:  0.15185996424670992
precision score of test:  0.1532027874465253

confusion_matrix of train:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
confusion_matrix of test:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### LogisticRegression

In [35]:
linear = LogisticRegression()
linear.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [36]:
print('accuracy score of test: ', linear.score(X_test, Y_test))

accuracy score of test:  0.1532027874465253


Opinion:  
I think that comparing performance is not that useful in my analysis because of the low score.  
It seems like if numbers of Y increase, the performance dramatically decreases.  
'Submiitted Via' has 6, but 'State' has 62.  
I guess that 'Company, 'Issue' and 'Product' will also have similar performance.  
Anyway, I will continue the test.

### Y = <span style="color:brown">'Company'</span>

In [37]:
X  = data03[['Product','Sub-product', 'Issue', 'State', 'Submitted via']].values
Y = data03['Company'].values

In [38]:
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))

In [39]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)

#### KNN

In [40]:
k = 100
my_model = KNeighborsClassifier(n_neighbors=k).fit(X_train, Y_train)
Ypredict = my_model.predict(X_test)

In [41]:
print('accuracy score of train: ',   metrics.accuracy_score(Y_train, my_model.predict(X_train)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, Ypredict))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, my_model.predict(X_train), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, Ypredict, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, my_model.predict(X_train), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, Ypredict, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, my_model.predict(X_train)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, Ypredict))

accuracy score of train:  0.185410705242799
accuracy score of test:  0.17183796365500012

recall score of train:  0.185410705242799
recall score of test:  0.17183796365500012

precision score of train:  0.185410705242799
precision score of test:  0.17183796365500012

confusion_matrix of train:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
confusion_matrix of test:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### LDA

In [42]:
lda = LDA()
X_train02 = lda.fit_transform(X_train, Y_train)
X_test02 = lda.transform(X_test)
y_predicted_test = lda.predict(X_test) 

In [43]:
print('accuracy score of train: ',   metrics.accuracy_score(Y_train, lda.predict(X_train02)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, y_predicted_test))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, lda.predict(X_train02), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, y_predicted_test, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, lda.predict(X_train02), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, y_predicted_test, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, lda.predict(X_train02)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, y_predicted_test))

accuracy score of train:  0.07248277923868676
accuracy score of test:  0.12725732630065414

recall score of train:  0.07248277923868676
recall score of test:  0.12725732630065414

precision score of train:  0.07248277923868676
precision score of test:  0.12725732630065414

confusion_matrix of train:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
confusion_matrix of test:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### LogisticRegression

It seems like using too much RAM..  
I think this is not that useful. If anyone runs the code below, It may run forever. 

In [ ]:
'''
linear = LogisticRegression()
linear.fit(X_train, Y_train)

print('accuracy score of test: ', linear.score(X_test, Y_test))
'''

Opinion:  
Too low performance to compare..  
Plus linear model is down because of too much load on RAM.  
As I said above, it is not that good for my analysis to compare.  
I will continue the test 'Issue' and 'Product'.

### Y = <span style="color:brown">'Issue'</span>

In [45]:
X  = data03[['Product','Sub-product','Company', 'State', 'Submitted via']].values
Y = data03['Issue'].values

In [46]:
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))

In [47]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)

#### KNN

In [48]:
k = 75
my_model = KNeighborsClassifier(n_neighbors=k).fit(X_train, Y_train)
Ypredict = my_model.predict(X_test)

In [49]:
print('accuracy score of train: ',   metrics.accuracy_score(Y_train, my_model.predict(X_train)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, Ypredict))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, my_model.predict(X_train), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, Ypredict, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, my_model.predict(X_train), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, Ypredict, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, my_model.predict(X_train)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, Ypredict))

accuracy score of train:  0.4953294976845779
accuracy score of test:  0.4834468669698976

recall score of train:  0.4953294976845779
recall score of test:  0.4834468669698976

precision score of train:  0.4953294976845779
precision score of test:  0.4834468669698976

confusion_matrix of train:  [[19516     0     0 ...     0     0     0]
 [   75    98     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [ 2708     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]
confusion_matrix of test:  [[8325    0    0 ...    0    0    0]
 [  39   36    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [1144    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]


#### LDA

In [50]:
lda = LDA()
X_train02 = lda.fit_transform(X_train, Y_train)
X_test02 = lda.transform(X_test)
y_predicted_test = lda.predict(X_test) 

In [51]:
print('accuracy score of train: ',   metrics.accuracy_score(Y_train, lda.predict(X_train02)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, y_predicted_test))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, lda.predict(X_train02), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, y_predicted_test, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, lda.predict(X_train02), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, y_predicted_test, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, lda.predict(X_train02)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, y_predicted_test))

accuracy score of train:  0.07612827255477392
accuracy score of test:  0.45857623837081013

recall score of train:  0.07612827255477392
recall score of test:  0.45857623837081013

precision score of train:  0.07612827255477392
precision score of test:  0.45857623837081013

confusion_matrix of train:  [[10743     0     0 ...     0     0     0]
 [  336     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [ 1642     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]
confusion_matrix of test:  [[9100    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [1461    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]


#### LogisticRegression

In [52]:
linear = LogisticRegression()
linear.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [53]:
print('accuracy score of test: ', linear.score(X_test, Y_test))

accuracy score of test:  0.4553090321524412


Opinion:  
Interesting..  
KNN looks slightly better than LDA.  
Also, LDA's train and test score's gap are large.  
Little bit low, but I think my guess is wrong that I mention above..

### Y = <span style="color:brown">'Product'</span>

In [54]:
X  = data03[['Sub-product','Issue', 'Company', 'State', 'Submitted via']].values
Y = data03['Product'].values

In [55]:
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))

In [56]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)

#### KNN

In [57]:
k= 1
my_model = KNeighborsClassifier(n_neighbors=k).fit(X_train, Y_train)
Ypredict = my_model.predict(X_test)

In [58]:
print('accuracy score of train: ',   metrics.accuracy_score(Y_train, my_model.predict(X_train)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, Ypredict))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, my_model.predict(X_train), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, Ypredict, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, my_model.predict(X_train), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, Ypredict, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, my_model.predict(X_train)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, Ypredict))

accuracy score of train:  1.0
accuracy score of test:  0.9872372532689857

recall score of train:  1.0
recall score of test:  0.9872372532689857

precision score of train:  1.0
precision score of test:  0.9872372532689857

confusion_matrix of train:  [[ 52190      0      0      0      0      0      0      0      0      0]
 [     0  18540      0      0      0      0      0      0      0      0]
 [     0      0  86500      0      0      0      0      0      0      0]
 [     0      0      0   3184      0      0      0      0      0      0]
 [     0      0      0      0 146267      0      0      0      0      0]
 [     0      0      0      0      0    561      0      0      0      0]
 [     0      0      0      0      0      0   3350      0      0      0]
 [     0      0      0      0      0      0      0   2217      0      0]
 [     0      0      0      0      0      0      0      0  14983      0]
 [     0      0      0      0      0      0      0      0      0     10]]
confusion_matrix o

#### LDA

In [59]:
lda = LDA()
X_train02 = lda.fit_transform(X_train, Y_train)
X_test02 = lda.transform(X_test)
y_predicted_test = lda.predict(X_test) 

In [60]:
print('accuracy score of train: ',   metrics.accuracy_score(Y_train, lda.predict(X_train02)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, y_predicted_test))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, lda.predict(X_train02), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, y_predicted_test, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, lda.predict(X_train02), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, y_predicted_test, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, lda.predict(X_train02)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, y_predicted_test))

accuracy score of train:  0.5439106533822247
accuracy score of test:  0.6760767900232761

recall score of train:  0.5439106533822247
recall score of test:  0.6760767900232761

precision score of train:  0.5439106533822247
precision score of test:  0.6760767900232761

confusion_matrix of train:  [[ 20371   4134   4673      0  23012      0      0      0      0      0]
 [   248   6606   7086      0   3421      0   1179      0      0      0]
 [ 15071   5231  40463      0  25735      0      0      0      0      0]
 [     0    199    309      0   2676      0      0      0      0      0]
 [  9352   3283  22759      0 110855      0     18      0      0      0]
 [    16     60    114      0    371      0      0      0      0      0]
 [   407    390   2450      0    103      0      0      0      0      0]
 [   145    725    361      0    986      0      0      0      0      0]
 [  2031   3566   7649      0   1737      0      0      0      0      0]
 [     0      0      0      0     10      0    

#### LogisticRegression

In [61]:
linear = LogisticRegression()
linear.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [62]:
print('accuracy score of test: ', linear.score(X_test, Y_test))

accuracy score of test:  0.6720693017859304


Opinion:  
The result shows KNN seems better than LDA.