<a href="https://colab.research.google.com/github/joohoshin/TensorflowAI/blob/main/4_2_Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 배열 자동 생성
* random을 통해서 자동으로 생성가능함
* randint(start, end, size = (row size, column size)) 형태로 사용 (end는 포함되지 않음)

In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(0,10, size=(2,3))
print(arr1, "\n")

arr2 = np.random.randint(0,10, size = 10)
print(arr2)

[[4 3 6]
 [5 4 1]] 

[2 4 8 3 3 9 3 2 3 4]


* rand(row size, column size)는 0~1 사이의 값을 랜덤 선택 (1은 미포함)


In [3]:
arr3 = np.random.rand(5,3)

print(arr3)

[[0.26837337 0.97954232 0.36427511]
 [0.24994081 0.19194915 0.16823577]
 [0.38691823 0.93722798 0.17541084]
 [0.72402269 0.09749065 0.70798156]
 [0.69005464 0.72197806 0.9568282 ]]


In [4]:
arr4 = np.random.rand(5,3)

print(arr4)

[[0.6379291  0.63307277 0.4024194 ]
 [0.9548933  0.26909911 0.1255286 ]
 [0.07249021 0.02933102 0.57248182]
 [0.71042579 0.93422871 0.05341375]
 [0.24089625 0.21304567 0.58490936]]


* 그 외에도 여러가지 행렬 연산 기능이 있음
* https://www.bogotobogo.com/python/python_numpy_matrix_tutorial.php

##### 주요 통계값
* 리스트와 마찬가지로 min(), count() 등 되며
* 평균 및 표준편차도 쉽게 구할 수 있다 mean(), std() 

In [5]:
print("sum : %.2f" % arr4.sum())
print("min : %.2f" % arr4.min())
print("max : %.2f" % arr4.max())
print("mean : %.2f" % arr4.mean())
print("std : %.2f" % arr4.std())
print("var : %.2f" % arr4.var())

sum : 6.43
min : 0.03
max : 0.95
mean : 0.43
std : 0.30
var : 0.09


##### 특정 범위 가져오기
* arr[start:end:step]으로 특정 범위 데이터를 가져올 수 있다
  (end 는 미포함)
* 리스트와 동일함

In [6]:
arr5 = np.random.randint(10, size = 10)

print(arr5)

[0 1 3 9 2 5 2 9 5 3]


In [7]:
arr5[:5] 

array([0, 1, 3, 9, 2])

In [8]:
arr5[1:3]

array([1, 3])